[application]
name = "s_e_e"
default_platform = "desktop"

[web.app]
title = "Speculative Execution Engine"

[web.dev]
proxy = ""

[bundle]
identifier = "com.s_e_e.workflow-engine"
publisher = "Speculative Execution Engine"
