# Configuration for cargo-release
# See: https://github.com/crate-ci/cargo-release/blob/master/docs/reference.md

# Apply version changes to all workspace members
[workspace]
consolidate-commits = true

# Don't publish to crates.io (this is a desktop app)
publish = false

# Tag format
tag-name = "v{{version}}"
tag-message = "Release {{tag_name}}"

# Commit message format
pre-release-commit-message = "chore: bump version to {{version}}"

# Don't sign commits and tags (handled by GitHub Actions bot)
sign-commit = false
sign-tag = false

# Don't verify builds before release (we do that in CI)
verify = false

# Allow releasing from main branch
allow-branch = ["main"]

# Enable tagging
tag = true

