version: '3'

tasks:
  # Build the application
  build:
    desc: Build the Rust application
    cmds:
      - cargo build

  # Run the application
  run:
    desc: Run the application
    cmds:
      - cargo run

  # Run tests
  test:
    desc: Run all tests
    cmds:
      - cargo test

  # Run tests with output
  test-verbose:
    desc: Run tests with verbose output
    cmds:
      - cargo test -- --nocapture

  # Run only integration tests
  test-integration:
    desc: Run integration tests only
    cmds:
      - cargo test --test integration_test

  # Run only GUI integration tests
  test-gui:
    desc: Run GUI integration tests only
    cmds:
      - cargo test --test gui_integration_test

  # Clean build artifacts
  clean:
    desc: Clean build artifacts
    cmds:
      - cargo clean

  # Check code without building
  check:
    desc: Check code for errors without building
    cmds:
      - cargo check

  # Format code
  fmt:
    desc: Format Rust code
    cmds:
      - cargo fmt

  # Run clippy linter
  lint:
    desc: Run clippy linter
    cmds:
      - cargo clippy

  # Download Tailwind CLI (one-time setup)
  tailwind-setup:
    desc: Download Tailwind standalone CLI
    cmds:
      - curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-macos-arm64
      - mv tailwindcss-macos-arm64 tailwindcss
      - chmod +x tailwindcss
    status:
      - test -f tailwindcss

  # Build Tailwind CSS
  tailwind-build:
    desc: Build Tailwind CSS
    deps: [tailwind-setup]
    cmds:
      - ./tailwindcss-v3 -i ./input.css -o ./assets/tailwind.css --content "./src/**/*.rs" --minify

  # Watch Tailwind CSS during development
  tailwind-watch:
    desc: Watch and rebuild Tailwind CSS
    deps: [tailwind-setup]
    cmds:
      - ./tailwindcss-v3 -i ./input.css -o ./assets/tailwind.css --content "./src/**/*.rs" --watch

  # Run GUI with Tailwind build
  run-gui:
    desc: Build Tailwind CSS and run GUI
    deps: [tailwind-build]
    cmds:
      - cargo run --bin gui

  # Build release with Tailwind
  build-gui-release:
    desc: Build GUI for release with Tailwind CSS
    deps: [tailwind-build]
    cmds:
      - cargo build --release --bin gui
