version: '3'

env:
  RUST_LOG: s_e_e_core=trace,s_e_e_gui=trace,s_e_e_engine=trace

tasks:
  quality:
    desc: Run all quality checks (formatting, linting, tests, file size)
    cmds:
      # Build assets first before quality checks
      - task: visualizer
      - task: tailwind
      - task: icons
      # Now run quality checks
      - cargo fmt -- --check
      - cargo clippy --all-targets --all-features -- -D warnings
      - cargo nextest run
      - |
        echo "Running npm audit for react-flow-app..."
        cd react-flow-app && npm audit --production
      - |
        echo "Running npm audit for tailwind..."
        cd tailwind && npm audit --production
      - |
        echo "Running npm audit for icons..."
        cd icons && npm audit --production
      - |
        find . -name "*.rs" -not -path "./target/*" | xargs wc -l | awk '$1 > 200 && $2 != "total" {print "⚠️  " $2 " (" $1 " lines) - create an aggressive refactoring plan that completely eliminates this bloated file by breaking it into focused, single-responsibility modules, removing all legacy patterns, deleting unused code without any #[allow(dead_code)] bullshit, and modernizing the API contracts - I want zero warnings, zero dead code, and a clean architecture that actually makes sense."}' | head -10

  run-gui:
    desc: Run GUI with dx CLI
    cmds:
      - task: tailwind
      - task: icons
      - task: visualizer
      - task: fmt
      - dx run --package s_e_e_gui

  clean:
    desc: Clean build artifacts
    cmds:
      - cargo clean
      - dx clean
      - rm -rf react-flow-app/node_modules
      - rm -rf tailwind/node_modules
      - rm -rf gui/assets/workflow-visualizer
      - rm -f gui/assets/tailwind.css

  fmt:
    desc: Format code
    internal: true
    cmds:
      - cargo fmt
      - cargo clippy

  tailwind:
    desc: Build Tailwind CSS for main GUI and React Flow apps
    internal: true
    dir: tailwind
    cmds:
      - npm install
      - npm run build

  icons:
    desc: Build SVG icons for the GUI app
    internal: true
    dir: icons
    cmds:
      - npm install
      - npm run build

  visualizer:
    desc: Build React Flow workflow visualizer
    internal: true
    dir: react-flow-app
    cmds:
      - npm install
      - npm run build

  clear-db:
    desc: Deletes the database completely and resets data directory
    cmds:
      - rm -f ~/.s_e_e/data.db
      - rm -f ~/.s_e_e/data.db-wal
      - rm -f ~/.s_e_e/data.db-shm
      - rm -f ~/.s_e_e/audit.redb
      - echo "✅ Database cleared successfully"