version: '3'

tasks:
  # Development workflow
  dev:
    desc: Format, lint, and test code
    cmds:
      - cargo fmt
      - cargo clippy
      - cargo test

  # Run CLI application
  run-cli:
    desc: Run CLI with workflow.json
    deps: [dev]
    cmds:
      - cargo run --bin cli -- workflow.json

  # Run GUI application
  run-gui:
    desc: Build Tailwind CSS and run GUI
    deps: [dev, tailwind-build]
    cmds:
      - cargo run --bin gui

  # Run all tests
  test:
    desc: Run all tests
    cmds:
      - cargo test

  # Build release binary
  build-release:
    desc: Build optimized release binary
    deps: [tailwind-build]
    cmds:
      - cargo build --release

  # Clean build artifacts
  clean:
    desc: Clean build artifacts
    cmds:
      - cargo clean

  # Internal: Download Tailwind CLI
  tailwind-setup:
    cmds:
      - curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-macos-arm64
      - mv tailwindcss-macos-arm64 tailwindcss
      - chmod +x tailwindcss
    status:
      - test -f tailwindcss

  # Internal: Build Tailwind CSS
  tailwind-build:
    deps: [tailwind-setup]
    cmds:
      - ./tailwindcss -i ./input.css -o ./assets/tailwind.css --content "./src/**/*.rs" --minify
