version: '3'

tasks:
  # Development workflow
  dev:
    desc: Format, lint, and test code
    cmds:
      - cargo fmt
      - cargo clippy

  # Run CLI application
  run-cli:
    desc: Run CLI with workflow.json
    deps: [dev]
    cmds:
      - cargo run -p cli -- --file workflow.json

  # Run GUI application
  run-gui:
    desc: Run GUI with dx CLI
    deps: [dev,tailwind-build]
    cmds:
      - dx run --package gui

  # Development server with hot-reloading
  serve-gui:
    desc: Start GUI development server with hot-reloading
    deps: [dev]
    cmds:
      - dx serve --package gui

  # Build release binary
  build-release:
    desc: Build optimized release binary with dx CLI
    deps: [dev]
    cmds:
      - dx build --package gui

  # Clean build artifacts
  clean:
    desc: Clean build artifacts
    cmds:
      - cargo clean
      - dx clean --package gui

  # Internal: Download Tailwind CLI
  tailwind-setup:
    cmds:
      - curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-macos-arm64
      - mv tailwindcss-macos-arm64 tailwindcss
      - chmod +x tailwindcss
    status:
      - test -f tailwindcss

  # Internal: Build Tailwind CSS
  tailwind-build:
    deps: [tailwind-setup]
    cmds:
      - ./tailwindcss -i ./input.css -o ./gui/assets/tailwind.css --config ./gui/tailwind.config.js --minify
